-- Generated by scripts/prepare_data.py; do not edit generated files.
BEGIN;
CREATE TABLE countries (id text PRIMARY KEY, name text NOT NULL UNIQUE);
CREATE TABLE observations (
 country_id text NOT NULL REFERENCES countries(id), source_country_name text NOT NULL,
 source_year integer NOT NULL, source_rank integer NOT NULL CHECK (source_rank > 0),
 score double precision NOT NULL CHECK (score BETWEEN 0 AND 10),
 ci_lower double precision, ci_upper double precision,
 gdp_contribution double precision, social_support_contribution double precision,
 healthy_life_contribution double precision, freedom_contribution double precision,
 generosity_contribution double precision, corruption_contribution double precision,
 dystopia_residual double precision,
 PRIMARY KEY (country_id, source_year),
 CHECK ((ci_lower IS NULL AND ci_upper IS NULL) OR (ci_lower IS NOT NULL AND ci_upper IS NOT NULL AND ci_lower <= score AND score <= ci_upper))
);
COMMIT;
