import {useState} from 'react';
import {factorLabels} from '@happiness/contracts';
import type {Country,ComparisonData,HistoryData,FactorKey} from '@happiness/contracts';
import {useApi} from '../api';
import {CountrySelect,LineChart,number,SectionTitle,signed,SourceBadge,Stat,Status,YearSelect} from '../components';
export function Compare({countries,years,year,onYear}:{countries:Country[];years:number[];year:number;onYear:(n:number)=>void}) {
  const [left,setLeft]=useState('germany'),[right,setRight]=useState('finland');
  const state=useApi<ComparisonData>(`/compare?countries=${left},${right}&year=${year}`);
  const a=useApi<HistoryData>(`/countries/${left}/history`),b=useApi<HistoryData>(`/countries/${right}/history`);
  const data=state.result?.data;
  return <><div className="page-intro"><span className="eyebrow">ZWEI PERSPEKTIVEN</span><h1>Gemeinsamkeiten. Unterschiede.</h1><p>Zwei Länder im direkten Vergleich – vom Score bis zu den erklärenden Faktoren.</p></div><div className="compare-controls"><CountrySelect label="Erstes Land" countries={countries.filter(c=>c.id!==right)} value={left} onChange={setLeft}/><span className="versus">vs.</span><CountrySelect label="Zweites Land" countries={countries.filter(c=>c.id!==left)} value={right} onChange={setRight}/><YearSelect years={years} value={year} onChange={onYear}/></div><Status {...state}/>
  {data&&<><div className="stats"><Stat accent label={data.countries[0].name} value={number(data.observations[0]?.score,3)} detail={data.observations[0]?`Rang ${data.observations[0].rank} · ${year}`:`Kein Wert für ${year}`}/><Stat label={data.countries[1].name} value={number(data.observations[1]?.score,3)} detail={data.observations[1]?`Rang ${data.observations[1].rank} · ${year}`:`Kein Wert für ${year}`}/><Stat label="Abstand im Score" value={data.scoreDifference===null?'—':signed(data.scoreDifference)} detail="Erstes minus zweites Land"/></div>
  <section className="panel"><SectionTitle kicker="BEITRÄGE ZUR MODELLERKLÄRUNG" title="Welche Faktoren zeigt die Quelle?"><SourceBadge source={state.result!.meta.source}/></SectionTitle><p className="muted">Die Werte sind modellierte Beiträge in Score-Punkten. Sie sind weder Geldbeträge noch Lebensjahre und belegen keine Kausalität.</p><div className="table-scroll"><table className="factor-table"><thead><tr><th>Faktor</th>{data.countries.map(c=><th className="numeric" key={c.id}>{c.name}</th>)}</tr></thead><tbody>{(Object.keys(factorLabels) as FactorKey[]).map(key=><tr key={key}><td>{factorLabels[key]}</td>{data.observations.map((r,i)=><td key={i} className="numeric"><div className="factor-cell"><span className={`tiny-bar ${i===1?'gold':''}`} style={{width:`${Math.max(0,r?.factors[key]??0)*24}px`}}/>{number(r?.factors[key],3)}</div></td>)}</tr>)}</tbody></table></div><p className="chart-note">„—“ = nicht vorhanden. Dystopia + Residuum kann negativ sein und wird nicht auf null gesetzt.</p></section></>}
  <section className="panel below"><SectionTitle title="Der gemeinsame Blick zurück"/><Status loading={a.loading||b.loading} error={a.error??b.error} retry={()=>{a.retry();b.retry();}}/>{a.result&&b.result&&<><LineChart series={[{name:a.result.data.country.name,values:a.result.data.observations,color:'#246254'},{name:b.result.data.country.name,values:b.result.data.observations,color:'#bf842e'}]}/><div className="chart-sources"><SourceBadge source={a.result.meta.source}/><SourceBadge source={b.result.meta.source}/></div><details><summary>Exakte Verlaufwerte anzeigen</summary><div className="table-scroll"><table><thead><tr><th>Quellenjahr</th><th className="numeric">{a.result.data.country.name}</th><th className="numeric">{b.result.data.country.name}</th></tr></thead><tbody>{years.map(y=><tr key={y}><td>{y}</td><td className="numeric">{number(a.result!.data.observations.find(r=>r.year===y)?.score,3)}</td><td className="numeric">{number(b.result!.data.observations.find(r=>r.year===y)?.score,3)}</td></tr>)}</tbody></table></div></details></>}</section></>;
}
