import type {Country,HistoryData} from '@happiness/contracts';
import {useApi} from '../api';
import {CountrySelect,LineChart,number,SectionTitle,signed,SourceBadge,Stat,Status} from '../components';
export function History({countries,countryId,onCountry}:{countries:Country[];countryId:string;onCountry:(s:string)=>void}) {
  const state=useApi<HistoryData>(`/countries/${countryId}/history`),data=state.result?.data;
  const first=data?.observations[0],last=data?.observations.at(-1);
  return <><div className="page-intro"><span className="eyebrow">ENTWICKLUNGEN ENTDECKEN</span><h1>Ein Land. Viele Zeitstände.</h1><p>Wie sich die Lebensbewertung im Lauf der Zeit verändert.</p></div><div className="toolbar"><CountrySelect label="Land / Gebiet" countries={countries} value={countryId} onChange={onCountry}/>{state.result&&<SourceBadge source={state.result.meta.source}/>}</div><Status {...state}/>
  {data&&first&&last&&<><div className="stats"><Stat accent label={data.country.name} value={number(last.score,3)} detail={`Letzter verfügbarer Wert · ${last.year}`}/><Stat label="Veränderung" value={signed(last.score-first.score)} detail={`Punkte von ${first.year} bis ${last.year}`}/><Stat label="Datenabdeckung" value={data.observations.length} detail="Vorhandene Zeitstände"/></div><section className="panel"><SectionTitle kicker="LEBENSBEWERTUNG IM VERLAUF" title={data.country.name}/><LineChart series={[{name:data.country.name,values:data.observations,color:'#246254'}]}/></section><section className="panel below"><SectionTitle title="Die Werte hinter dem Diagramm"/><p className="muted">Fehlende Zeitstände bleiben offen. Ein Strich bedeutet: kein Konfidenzintervall in der Quelle.</p><div className="table-scroll"><table><thead><tr><th>Quellenjahr</th><th className="numeric">Originalrang</th><th className="numeric">Score</th><th className="numeric">95%-Konfidenzintervall</th></tr></thead><tbody>{[...data.observations].reverse().map(r=><tr key={r.year}><td>{r.year}</td><td className="numeric">{r.rank}</td><td className="numeric score">{number(r.score,3)}</td><td className="numeric">{r.lower===null?'—':`${number(r.lower,3)} – ${number(r.upper,3)}`}</td></tr>)}</tbody></table></div></section></>}
  {data&&!data.observations.length&&<p className="state">Für dieses Land sind keine Beobachtungen vorhanden.</p>}</>;
}
