import {useState} from 'react';
import type {RankingsData} from '@happiness/contracts';
import {useApi,useDebounce} from '../api';
import {Icon,number,SectionTitle,SourceBadge,Stat,Status,YearSelect} from '../components';
export function Overview({years,year,onYear,onCountry}:{years:number[];year:number;onYear:(y:number)=>void;onCountry:(id:string)=>void}) {
  const [search,setSearch]=useState(''),[offset,setOffset]=useState(0),[order,setOrder]=useState('desc');
  const q=useDebounce(search);
  const state=useApi<RankingsData>(`/rankings?year=${year}&q=${encodeURIComponent(q)}&limit=15&offset=${offset}&order=${order}`);
  const data=state.result?.data;
  return <><section className="hero"><div><span className="eyebrow light">DER DATENATLAS ZUR LEBENSZUFRIEDENHEIT</span><h1>Wie glücklich<br/>ist die Welt?</h1><p>Länder entdecken. Entwicklungen einordnen.<br/>Die Geschichten hinter den Zahlen verstehen.</p></div><div className="hero-visual" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><div className="hero-number">0—10<span>Eine Frage.<br/>Viele Perspektiven.</span></div><span className="hero-star">✦</span></div></section>
    <div className="toolbar"><div><h2>Die Welt im Vergleich</h2><p className="muted">{year===2025?'Bericht 2026 · Erhebungszeitraum 2023–2025':'Historischer Zeitstand · Mehrjahresmittel'}</p></div><YearSelect years={years} value={year} onChange={y=>{setOffset(0);onYear(y);}}/></div>
    <Status {...state}/>{data&&<><div className="stats"><Stat label="Länder & Gebiete" value={data.summary.count} detail={`im Quellenjahr ${year}`}/><Stat label="Mittlere Lebensbewertung" value={<>{number(data.summary.meanScore)}<small>/ 10</small></>} detail="Ungewichtetes Mittel der Länder"/><Stat accent label="Höchste Lebensbewertung" value={data.summary.leader.countryName} detail={`${number(data.summary.leader.score,3)} Punkte · Rang ${data.summary.leader.rank}`}/></div>
    <div className="overview-grid"><section className="panel"><SectionTitle kicker="DAS RANKING" title="Länder im Überblick"><SourceBadge source={state.result!.meta.source}/></SectionTitle>
      <div className="table-controls"><label className="search"><Icon name="search"/><input aria-label="Land im Ranking suchen" placeholder="Land suchen, z. B. Germany" value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}}/></label><select aria-label="Ranking sortieren" value={order} onChange={e=>{setOrder(e.target.value);setOffset(0);}}><option value="desc">Höchster Score zuerst</option><option value="asc">Niedrigster Score zuerst</option></select></div>
      <div className="table-scroll"><table><thead><tr><th>Rang</th><th>Land / Gebiet</th><th className="numeric">Score</th><th className="score-column">Lebensbewertung</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{data.rows.map(r=><tr key={r.countryId}><td><span className={`rank ${r.rank<=3?'top':''}`}>{r.rank.toString().padStart(2,'0')}</span></td><td><button className="country-link" onClick={()=>onCountry(r.countryId)}>{r.countryName}</button></td><td className="numeric score">{number(r.score,3)}</td><td className="score-column"><span className="score-track"><i style={{width:`${r.score*10}%`}}/></span></td><td><button className="arrow-button" aria-label={`Zeitverlauf ${r.countryName}`} onClick={()=>onCountry(r.countryId)}>↗</button></td></tr>)}</tbody></table></div>
      {!data.rows.length&&<p className="empty">Kein Land zu „{q}“ gefunden.</p>}<div className="pagination"><span>{data.total?`${offset+1}–${Math.min(offset+15,data.total)}`:'0'} von {data.total} Ländern</span><div><button disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-15))} aria-label="Vorherige Seite">←</button><button disabled={offset+15>=data.total} onClick={()=>setOffset(offset+15)} aria-label="Nächste Seite">→</button></div></div>
    </section><aside className="side-panels"><section className="panel leaders"><span className="eyebrow">DIE SPITZENGRUPPE</span><h2>Acht Länder, ein Blick</h2><p className="muted">Lebensbewertung auf einer Skala von 0 bis 10.</p>{data.leaders.map((r,i)=><button key={r.countryId} className="leader-row" onClick={()=>onCountry(r.countryId)}><span><b>{r.countryName}</b><em>{number(r.score,2)}</em></span><i className="leader-track"><i style={{width:`${r.score*10}%`,background:i===0?'#dba557':'#2b685c'}}/></i></button>)}</section><section className="note-card"><Icon name="source"/><h3>Was bedeutet „glücklich“?</h3><p>Menschen bewerten ihr eigenes Leben von 0 bis 10. Das Ranking beruht auf diesen Antworten, nicht auf der Summe der erklärenden Faktoren.</p><a href="#source">Zur Datenbasis <span>↗</span></a></section></aside></div></>}
  </>;
}
