import {useState} from 'react';
import type {TrendsData} from '@happiness/contracts';
import {useApi} from '../api';
import {number,SectionTitle,signed,SourceBadge,Stat,Status,YearSelect} from '../components';
export function Trends({years,onCountry}:{years:number[];onCountry:(id:string)=>void}) {
  const [from,setFrom]=useState(2018),[to,setTo]=useState(years.at(-1)!),[search,setSearch]=useState('');
  const state=useApi<TrendsData>(`/insights/trends?from=${from}&to=${to}`),data=state.result?.data;
  const rows=data?.rows.filter(r=>r.countryName.toLowerCase().includes(search.toLowerCase()))??[];
  return <><div className="page-intro"><span className="eyebrow">VERÄNDERUNGEN SICHTBAR MACHEN</span><h1>Wo bewegt sich etwas?</h1><p>Verglichen werden nur Länder, für die an beiden Zeitständen ein Wert vorliegt.</p></div><div className="toolbar"><div className="range-controls"><YearSelect years={years.filter(y=>y<to)} label="Von Quellenjahr" value={from} onChange={setFrom}/><span>→</span><YearSelect years={years.filter(y=>y>from)} label="Bis Quellenjahr" value={to} onChange={setTo}/></div>{state.result&&<SourceBadge source={state.result.meta.source}/>}</div><Status {...state}/>
  {data&&<><div className="stats"><Stat label="Vergleichbare Länder" value={data.matchedCountries} detail={`${data.excludedCountries} Länder wegen Datenlücken ausgeschlossen`}/><Stat accent label="Mittlere Veränderung" value={signed(data.meanChange)} detail="Ungewichtetes Mittel derselben Länder"/><Stat label="Zeitraum" value={`${from}–${to}`} detail="Differenz der veröffentlichten Mehrjahresmittel"/></div><div className="trend-grid">{[{title:'Größte Zunahmen',rows:data.rows.filter(r=>r.change>0).slice(0,5),positive:true},{title:'Größte Rückgänge',rows:[...data.rows].reverse().filter(r=>r.change<0).slice(0,5),positive:false}].map(group=><section className="panel" key={group.title}><SectionTitle title={group.title}/>{group.rows.length===0&&<p>Keine passenden Veränderungen.</p>}{group.rows.map(r=><button className="change-row" key={r.countryId} onClick={()=>onCountry(r.countryId)}><span>{r.countryName}</span><strong className={group.positive?'positive':'negative'}>{signed(r.change)}</strong></button>)}</section>)}</div><section className="panel below"><SectionTitle title="Alle Veränderungen"/><label className="search standalone"><input placeholder="Land suchen …" aria-label="Land in Veränderungen suchen" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="table-scroll"><table><thead><tr><th>Land / Gebiet</th><th className="numeric">{from}</th><th className="numeric">{to}</th><th className="numeric">Δ Punkte</th></tr></thead><tbody>{rows.map(r=><tr key={r.countryId}><td><button className="country-link" onClick={()=>onCountry(r.countryId)}>{r.countryName}</button></td><td className="numeric">{number(r.fromScore,3)}</td><td className="numeric">{number(r.toScore,3)}</td><td className={`numeric score ${r.change>=0?'positive':'negative'}`}>{signed(r.change)}</td></tr>)}</tbody></table></div>{!rows.length&&<p className="empty">Keine passenden Länder gefunden.</p>}<p className="chart-note">Beschreibender Vergleich ohne Signifikanztest. Überlappende Erhebungszeiträume und veränderte Stichproben berücksichtigen.</p></section></>}
  </>;
}
